sudo: request
services:
  - docker

before_install:
  - docker build -t dockerImage -f Dockerfile.dev .

# script that can be runned by travis on our container

script:
  - docker run dockerImage npm run test -- --coverage
